# Generated by Django 5.2 on 2025-04-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('matricule', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default='blue', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='blue', max_length=100)),
            ],
        ),
    ]
