# Generated by Django 5.2 on 2025-04-18 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default='blue', max_length=100)),
                ('description', models.CharField(default='blue', max_length=100)),
                ('surperficie', models.FloatField()),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.gestionnaire')),
            ],
        ),
    ]
