# Generated by Django 5.2 on 2025-04-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartier',
            name='description',
            field=models.TextField(),
        ),
    ]
