# Generated by Django 5.2 on 2025-04-16 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='blue', max_length=100)),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.gestionnaire')),
            ],
        ),
    ]
