# Generated by Django 5.2 on 2025-04-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
