# Generated by Django 5.2 on 2025-04-18 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0002_alter_categorie_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adresse', models.CharField(default='blue', max_length=100)),
                ('description', models.CharField(default='blue', max_length=100)),
                ('surperficie', models.FloatField(unique=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorie.categorie')),
            ],
        ),
    ]
