# Generated by Django 5.2 on 2025-04-18 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maison', '0001_initial'),
        ('quartier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartier.quartier'),
        ),
    ]
