# Generated by Django 5.2 on 2025-04-18 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0001_initial'),
        ('maison', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='gestionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.gestionnaire'),
            preserve_default=False,
        ),
    ]
