# Generated by Django 5.2 on 2025-04-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0003_maison_gestionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maison',
            name='description',
        ),
        migrations.AlterField(
            model_name='maison',
            name='adresse',
            field=models.CharField(default='blue', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='maison',
            name='surperficie',
            field=models.FloatField(),
        ),
    ]
